name: Deploy Python App to Azure Web App - PDF-ChatBot

on:
  workflow_dispatch:  # Can be triggered manually

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PDF-ChatBot'
          slot-name: 'Production'
          package: .

      - name: Set startup command
        run: |
          az webapp config set \
            --resource-group pdf-chatbot-rg \
            --name PDF-ChatBot \
            --startup-file "gunicorn --bind=0.0.0.0:8000 app:app"
