name: Build and deploy Python app to Azure Web App - PDF-ChatBot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python version
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        pip install --no-cache-dir -r requirements.txt
        pip install chromadb==0.4.15 --no-deps
        pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu

    - name: Create required directories
      run: mkdir -p pdfs chroma_store

    - name: Download NLTK data
      run: python -c "import nltk; nltk.download('stopwords', quiet=True)"

    - name: Prepare deployment package
      run: |
        # Remove unnecessary files
        rm -rf venv/
        find . -type d -name __pycache__ -delete
        find . -name "*.pyc" -delete
        
        # Create startup script for Azure
        echo "#!/bin/bash" > startup.sh
        echo "python -m pip install --upgrade pip" >> startup.sh
        echo "pip install -r requirements.txt" >> startup.sh
        echo "python -c \"import nltk; nltk.download('stopwords', quiet=True)\"" >> startup.sh
        echo "mkdir -p pdfs chroma_store" >> startup.sh
        echo "gunicorn --bind 0.0.0.0:8000 --timeout 600 --workers 2 app:app" >> startup.sh
        chmod +x startup.sh

        # Zip everything (excluding junk)
        zip -r release.zip . -x "venv/*" ".git/*" ".github/*"

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v4
      with:
        name: python-app
        path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      contents: read

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: python-app
        path: .

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      id: deploy-to-webapp
      with:
        app-name: 'PDF-ChatBot'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: release.zip
