name: Build and deploy Python app to Azure Web App - PDF-ChatBot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

     # Step 4: Prepare clean deploy folder
      - name: Prepare deploy folder
        run: |
          mkdir deploy-folder
          cp app.py requirements.txt deploy-folder/
          # Copy folders only if they exist
          [ -d templates ] && cp -r templates deploy-folder/ || echo "templates folder not found"
          [ -d pdfs ] && cp -r pdfs deploy-folder/ || echo "pdfs folder not found"
          [ -d chroma_store ] && cp -r chroma_store deploy-folder/ || echo "chroma_store folder not found"

      # Step 5: Upload deploy artifact
      - name: Upload deploy artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deploy-folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read

    steps:
      # Step 1: Download deploy artifact
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: deploy-folder

      # Step 2: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PDF-ChatBot'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./deploy-folder
          configuration-strings: 'SCM_DO_BUILD_DURING_DEPLOYMENT=true'


      # Step 3: Configure startup command
      - name: Configure startup command
        run: |
          az webapp config set \
            --resource-group pdf-chatbot-rg \
            --name PDF-ChatBot \
            --startup-file "gunicorn --bind=0.0.0.0 --timeout 600 app:app"
