name: Build and deploy Python app to Azure Web App - PDF-ChatBot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: run tests
      # - name: Run tests
      #   run: pytest

      # Step 4: Prepare clean deploy folder
      - name: Prepare deploy folder
        run: |
          mkdir deploy-folder
          cp app.py requirements.txt deploy-folder/
          cp -r templates static pdfs chroma_store deploy-folder/

      # Step 5: Upload deploy folder as artifact
      - name: Upload deploy artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deploy-folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read

    steps:
      # Step 1: Download deploy artifact
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: deploy-folder

      # Step 2: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PDF-ChatBot'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./deploy-folder
