name: Build and deploy Python app to Azure Web App - PDF-ChatBot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional test step
      # - name: Run tests
      #   run: pytest

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            app.py
            requirements.txt
            static/
            templates/
            pdfs/
            chroma_store/
            !venv/
            !.git/
            !__pycache__/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Deploy to Azure Web App using Publish Profile
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PDF-ChatBot'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .  # now artifact root, not entire repo
