name: Deploy Python App to Azure Web App - PDF-ChatBot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python (optional, just to validate build)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install chromadb==0.4.15 --no-deps
          pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
          python -c "import nltk; nltk.download('stopwords', quiet=True)"

      # 3. Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pdf-chatbot'   # must match Azure App Service name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
