name: Deploy PDF-ChatBot to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for OIDC
      contents: read    # Required to checkout code

    steps:
      # 1. Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Azure Login via OIDC
      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          enable-oidc: true
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 5. Deploy app to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PDF-ChatBot'
          slot-name: 'Production'
          package: .

      # 6. Set startup command (Gunicorn for Flask)
      - name: Set startup command
        run: |
          az webapp config set \
            --resource-group pdf-chatbot-rg \
            --name PDF-ChatBot \
            --startup-file "gunicorn --bind=0.0.0.0:8000 app:app"
