name: Deploy PDF-ChatBot to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write       # Required for OIDC
      contents: read        # Required to checkout code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Azure login via OIDC
        uses: azure/login@v2
        with:
          scope: "https://management.azure.com/.default"
          enable-oidc: true
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PDF-ChatBot'
          slot-name: 'Production'
          package: .

      - name: Set startup command
        run: |
          az webapp config set \
            --resource-group pdf-chatbot-rg \
            --name PDF-ChatBot \
            --startup-file "gunicorn --bind=0.0.0.0:8000 app:app"
